spring:
  cloud:
    gateway:
      routes:
        - id: msvc-cursos
          uri: lb://msvc-cursos
          predicates:
            - Path=/api/cursos/**
          filters:
            - StripPrefix=2
        - id: msvc-usuario
          uri: lb://msvc-usuario
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2
