
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: msvc-usuario
  data:
    port: "8001"
    db_host: "mysql8:3306"
    database: "msvc_usuarios"
    curso_url: "msvc-cursos:8002"
    lb_auth_issuer_uri: "http://host.docker.internal:51258"
    lb_usuarios_uri: "http://host.docker.internal:51234"

    application.yml: |-
      config:
        texto: Configurando ambiente por defecto
      ---  
      spring:
        config:
          on-activate: dev
      config:
        texto: Configurando ambiente de desarrollo
      ---
      spring:
        config:
          on-activate: prod
      config:
        texto: Configurando ambiente de produccion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres12:5432"
  database: "msvc_cursos"
  usuario_url: "msvc-usuario:8001"