apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres12
          image: postgres:12-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: 63.Lafa.96
            - name: POSTGRES_DB
              value: msvc_cursos

