version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres12:
    container_name: postgres12
    image: postgres:12-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 63.Lafa.96
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-usuario:
    container_name: msvc-usuario
    image: luchan632/msvc-usuario:v1
#    build:
#      context: ./
#      dockerfile: ./msvc-usuario/Dockerfile
#    image: msvc-usuario:v1
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: sasa
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  msvc-cursos:
    container_name: msvc-cursos
    image: luchan632/msvc-cursos:v1
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
#    image: msvc-cursos:v1
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres12:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: 63.Lafa.96
      USUARIOS_URL: msvc-usuario:8001
    networks:
      - spring
    depends_on:
      - postgres12
      - msvc-usuario
    restart: always
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  spring:
