version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  msvc-usuario:
    container_name: msvc-usuario
    image: luchan632/msvc-usuario:v1
#    build:
#      context: ./
#      dockerfile: ./msvc-usuario/Dockerfile
#    image: msvc-usuario:v1
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: sasa
      CURSOS_URL: ec2-15-237-128-250.eu-west-3.compute.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
volumes:
  data-mysql:
    name: data-mysql
networks:
  spring:
