apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi # esto significa la capacidad en gb
  volumeMode: Filesystem
  storageClassName: standard # es muy importante buscarlok
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql
    type: DirectoryOrCreate