apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuario
type: Opaque
data:
  username: cm9vdA==
  password: c2FzYQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: NjMuTGFmYS45Ng==